name: nutri_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  go_router: ^6.5.9
  provider: ^6.0.3
  webview_flutter: ^3.0.4
  http: ^1.1.2
  flutter_dotenv: ^5.0.2
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.3
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  file_picker: ^6.1.1
  path: ^1.8.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
  assets:
    - lib/assets/logo.jpeg